# Dockerfile.rails
# from: https://semaphoreci.com/community/tutorials/dockerizing-a-ruby-on-rails-application

FROM ruby:3.2.1 AS pcfer-toolbox

# Default directory
ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH

# Install rails
RUN gem install rails bundler
WORKDIR /opt/app

# Run a shell
CMD ["/bin/sh"]
