version: "3.9"

services:

  seller-postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: supnet
      POSTGRES_PASSWORD: test_db_password
    ports:
      - '6543:5432'
    volumes:
      - seller-postgres:/var/lib/postgresql/data

  seller-pactifier:
    build:
      context: .
    volumes:
      - ./supnet:/opt/app
    links:
      - seller-postgres
    ports:
      - '3030:3000'
    env_file:
      - .seller.env

  buyer-postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: supnet
      POSTGRES_PASSWORD: test_db_password
    ports:
      - '6544:5432'
    volumes:
      - buyer-postgres:/var/lib/postgresql/data

  buyer-pactifier:
    build:
      context: .
    volumes:
      - ./supnet:/opt/app
    links:
      - buyer-postgres
    ports:
      - '3000:3000'
    env_file:
      - .buyer.env

volumes:
  seller-postgres:
  buyer-postgres:
  supnet: