version: "3.9"

services:

  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: supnet
      POSTGRES_PASSWORD: test_db_password
    volumes:
      - supnet-postgres:/var/lib/postgresql/data

  supnet:
    build:
      context: .
    volumes:
      - ./supnet:/opt/app
    links:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env

volumes:
  supnet-postgres: